options:
  env:
    type: string
    default: "dev"
    description: "Application environment."
  log-level:
    type: string
    default: "info"
    description: |
        Available log level settings are "info", "warning", "error" and "debug".
