name: Build/Test Charm

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: |
          cd vm_operator
          tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: |
          cd vm_operator
          tox -e unit

  functional-test:
    name: Functional tests
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Setup LXD
        uses: canonical/setup-lxd@4e959f8e0d9c5feb27d44c5e4d9a330a782edee0
      - name: Run tests
        run: |
          cd vm_operator
          tox -e functional

  integration-test:
    name: Integration tests
    runs-on: ubuntu-22.04
    needs:
      - lint
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup hosts for tests
        run: |
          echo "10.64.140.43 testing-ratings.foo.bar" | sudo tee -a /etc/hosts
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3.2/stable
      - name: Run integration tests
        run: |
          cd vm_operator
          tox -e integration -- --model=testing
